version: '3.7'

services:
  web:
    image: parnpresso/simplezat:unstable
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
