version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            echo 'hello'
  static_analysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            echo 'hello'
  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            echo 'hello'
  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            echo 'hello'

workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_analysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests
