version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pip3 install pipenv
            pipenv install --dev
  static_analysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run static analysis
          command: |
            pipenv install --dev
            pipenv run flake8
  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit test
          command: |
            cd simplezat
            pipenv install --dev
            pipenv run python manage.py test
  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t parnpresso/simplezat:stable -f Dockerfile.dev .
            docker push parnpresso/simplezat:stable
      - add_ssh_keys
      - run:
          name: Deploy to Dev Server
          command: |
            cd deployment
            ssh-keyscan -H 35.198.237.174 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook playbooks/dev.yml --extra-vars "project_path=~/simplezat"
  deploy_production:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Live Images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t parnpresso/simplezat:stable -f Dockerfile.dev .
            docker push parnpresso/simplezat:live
      - add_ssh_keys
      - run:
          name: Deploy to Production Server
          command: |
            cd deployment
            ssh-keyscan -H 35.240.179.3 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook playbooks/prod.yml --extra-vars "project_root=~/simplezat"

workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_analysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests
      - wait_for_approval:
          type: approval
          requires:
            - deploy_dev
      - deploy_production:
          requires:
            - wait_for_approval
